### ISSUE TITLE
403 Forbidden when I downloaded the dataset

### ISSUE THREAD

**Issue by Lykr** [lasseufpa/5gm-data#4]
I want to download the dataset "urban_canyon_v2i_5gmv1_rays.npz.zip" for research. 
But when I tried to download it from "https://owncloud.lasseufpa.org/s/wLCtqEYwHiSqMU1".
The website show me a 403 Forbidden message.

Could you please tell me where else I can download this dataset?

**Comment by aldebaro** [comment]
Sorry. We are reorganizing things at https://www.lasse.ufpa.br/raymobtime/

**Comment by AiltonOliveir** [comment]
the dataset "urban_canyon_v2i_5gmv1_rays.npz.zip" can now be download from "https://nextcloud.lasseufpa.org/s/5jaerkazjycbrsC"

**Comment by ocatak** [comment]
This link is not working.

**Comment by AiltonOliveir** [comment]
Please, check our wiki (
https://github.com/lasseufpa/5gm-data/wiki/Freely-available-data-for-machine-learning-applied-to-telecommunications)
all links are already updated.
The dataset is in this wiki, and you can found it in
https://nextcloud.lasseufpa.org/s/PKYwAbg6BYFqFi3

Em seg., 8 de fev. de 2021 às 17:14, Ferhat Ozgur Catak <
notifications@github.com> escreveu:

**Comment by RahulSinghGulia** [comment]
I am not able to download any dataset from any given link. Is it still available there, or has it moved to some other place. 

Thanks,
Rahul

**Comment by AiltonOliveir** [comment]
Dear Rahul,

We are doing maintenance on our servers, the links should be working normally from tuesday (UTC-3).
Thank you for understanding.
