### ISSUE TITLE
Generating data

### ISSUE THREAD

**Issue by Yaoyaobuku** [lasseufpa/5gm-data#6]
Hello! How can I generate the data I need after the installation is successful?

**Comment by prateekbhadauria** [comment]
you just need to make the following changes in the respective matlab code file 
1) insitePath= give here your path where your dataset is placed.

At this line of code which is line no 23,you will specified which episode you want to run ,after making  following changes its works well.
2) allEpisodeData=h5read('urban_canyon_v2i_5gmv1_rays_e84.hdf5','/allEpisodeData');

**Comment by Yaoyaobuku** [comment]
Thank you very much for your patience, I will try to run it.




------------------ 原始邮件 ------------------
发件人: "prateekbhadauria"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 晚上7:20
收件人: "lasseufpa/5gm-data"<5gm-data@noreply.github.com>;
抄送: "嫣梓筱畵酼"<1287227284@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [lasseufpa/5gm-data] Generating data (#6)




you just need to make the following changes in the respective matlab code file
  
insitePath= give here your path where your dataset is placed.
  
At this line of code which is line no 23,you will specified which episode you want to run ,after making  following changes its works well.
 2) allEpisodeData=h5read('urban_canyon_v2i_5gmv1_rays_e84.hdf5','/allEpisodeData');
